version: 2
jobs:
    build:
        docker:
            - image: cypress/base:8

        working_directory: ~/repo

        steps:
            - checkout

            - restore_cache:
                  keys:
                      - v1-deps-{{ checksum "yarn.lock" }}

            - run: yarn install

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "yarn.lock" }}

            # - run:
            #       command: yarn build:dev

            - run:
                  command: yarn start
                  background: true

            - run: yarn lint
            - run: yarn test --verbose
            - run: yarn cy:run
            - run: yarn chromatic --exit-zero-on-changes

            - store_artifacts:
                path: cypress/screenshots
